server:
  port: 8763

spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://42.192.132.55:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/